version: "3.8"

services:
  nextjs:
    image: nextjs-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - uploads-data:/app/uploads
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/Octech
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  uploads-data:
  mongo-data:

networks:
  app-network:
    driver: bridge
