export interface Department {
  title: string;
  icon: string;
  roomNumber: number;
}

const departments: Department[] = [
  { title: "Reception", icon: "👋", roomNumber: 1 },
  { title: "Registration", icon: "📋", roomNumber: 2 },
  { title: "Triage", icon: "🔍", roomNumber: 3 },
  { title: "Emergency", icon: "🚨", roomNumber: 4 },
  { title: "Laboratory", icon: "🧪", roomNumber: 5 },
  { title: "Radiology", icon: "📸", roomNumber: 6 },
  { title: "MRI", icon: "🔬", roomNumber: 7 },
  { title: "CT Scan", icon: "📽️", roomNumber: 8 },
  { title: "Ultrasound", icon: "🎥", roomNumber: 9 },
  { title: "Blood Bank", icon: "🩸", roomNumber: 10 },
  { title: "General Medicine", icon: "👨‍⚕️", roomNumber: 11 },
  { title: "Cardiology", icon: "❤️", roomNumber: 12 },
  { title: "Neurology", icon: "🧠", roomNumber: 13 },
  { title: "Orthopedics", icon: "🦴", roomNumber: 14 },
  { title: "Pediatrics", icon: "🧒", roomNumber: 15 },
  { title: "Surgery", icon: "⚔️", roomNumber: 16 },
  { title: "ICU", icon: "💓", roomNumber: 17 },
  { title: "Pharmacy", icon: "💊", roomNumber: 18 },
  { title: "Physiotherapy", icon: "🤸", roomNumber: 19 },
  { title: "Billing", icon: "💰", roomNumber: 20 },
  { title: "Cashier", icon: "💵", roomNumber: 21 },
  { title: "Discharge", icon: "🚪", roomNumber: 22 },
  { title: "Oncology", icon: "🎗️", roomNumber: 23 },
  { title: "Dermatology", icon: "🧴", roomNumber: 24 },
  { title: "Gastroenterology", icon: "🍽️", roomNumber: 25 },
  { title: "Endocrinology", icon: "🧬", roomNumber: 26 },
  { title: "Nephrology", icon: "🩺", roomNumber: 27 },
  { title: "Urology", icon: "🚻", roomNumber: 28 },
  { title: "Pulmonology", icon: "🫁", roomNumber: 29 },
  { title: "Rheumatology", icon: "🤝", roomNumber: 30 },
  { title: "Hematology", icon: "🩺", roomNumber: 31 },
  { title: "Infectious Diseases", icon: "🦠", roomNumber: 32 },
  { title: "Psychiatry", icon: "🧠", roomNumber: 33 },
  { title: "Obstetrics", icon: "🤰", roomNumber: 34 },
  { title: "Gynecology", icon: "♀️", roomNumber: 35 },
  { title: "Neonatology", icon: "👶", roomNumber: 36 },
  { title: "Ophthalmology", icon: "👁️", roomNumber: 37 },
  { title: "ENT (Ear, Nose, Throat)", icon: "👂", roomNumber: 38 },
  { title: "Dentistry", icon: "🦷", roomNumber: 39 },
  { title: "Nutrition", icon: "🥗", roomNumber: 40 },
  { title: "Rehabilitation", icon: "🏋️", roomNumber: 41 },
  { title: "Palliative Care", icon: "🕊️", roomNumber: 42 },
  { title: "Maternity Ward", icon: "👩‍🍼", roomNumber: 43 },
  { title: "Operating Theatre", icon: "🏥", roomNumber: 44 },
  { title: "Anesthesiology", icon: "😴", roomNumber: 45 },
  { title: "Pathology", icon: "🔬", roomNumber: 46 },
  { title: "Medical Records", icon: "📁", roomNumber: 47 },
  { title: "Human Resources", icon: "👥", roomNumber: 48 },
  { title: "Maintenance", icon: "🔧", roomNumber: 49 },
  { title: "Housekeeping", icon: "🧹", roomNumber: 50 },
  { title: "Security", icon: "🔒", roomNumber: 51 },
  { title: "Chaplaincy", icon: "🙏", roomNumber: 52 },
  { title: "Social Services", icon: "🤝", roomNumber: 53 },
  { title: "Patient Transport", icon: "🚑", roomNumber: 54 },
  { title: "Medical Imaging", icon: "🖼️", roomNumber: 55 },
  { title: "Outpatient Clinic", icon: "🏣", roomNumber: 56 },
];

export default departments;
